### ISSUE TITLE
Following redirects

### ISSUE THREAD

**Issue by metalmini** [shopsys/http-smoke-testing#5]
Hi there,

I am currently implementing a smoke test for an application with a lot of routes. I was wondering if there was a clever way to follow redirects if they occur?

Thanks in advance

**Comment by PetrHeinz** [comment]
Hello, as this tool checks all routes it seems to me that following redirects would lead to duplicating checked routes.

Example:
- There are routes A and B.
- B redirects to A.
- Smoke tests should check that A is 200 OK and B is 301 Moved Permanently

If it would follow redirects, the tests would basically check that A is 200 OK twice.

Do you have some specific use case in mind?

**Comment by metalmini** [comment]
That is a good point. I am quite new to smoke testing, so forgive my ignorance.

So to be more of a strict smoke test i should only check if the route returns a 302 and then call it a day?

The problem i am having is that this application is not built by me, and has a crapload of routes. Some are used, others not. So i am filtering the routes that work to get to the routes that throw errors and fix or delete them.

But checking for a 302 is good enough for me in this case. The followed redirect should be tested on its own.

Well i am going to close this, since i can check for 302's. Thanks for the quick reply!

**Comment by PetrHeinz** [comment]
Sure thing :) Good luck!
